<a href="https://colab.research.google.com/github/19PA1A04B3/Python-basics/blob/master/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
a=a.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype

dtype('int64')

In [7]:
a.itemsize

8

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

In [11]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.empty((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [42]:
b=np.random.random((2,3))
b

array([[0.77425244, 0.62740445, 0.91673157],
       [0.63806077, 0.4124943 , 0.02312708]])

In [49]:
c=np.array([10,20,30,40,50])
d=np.arange(5)
print(c)
print(d)

[10 20 30 40 50]
[0 1 2 3 4]


In [50]:
e=c-d
e

array([10, 19, 28, 37, 46])

In [52]:
e=c+d
e

array([10, 21, 32, 43, 54])

In [53]:
f=d**2
f

array([ 0,  1,  4,  9, 16])

In [54]:
f=d*2
f

array([0, 2, 4, 6, 8])

In [58]:
print(10*np.sin(a))

[[ 0.          8.41470985  9.09297427  1.41120008 -7.56802495]
 [-9.58924275 -2.79415498  6.56986599  9.89358247  4.12118485]
 [-5.44021111 -9.99990207 -5.36572918  4.20167037  9.90607356]]


In [59]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [62]:
print(a<10)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [False False False False False]]


In [63]:
a[0]+2

array([2, 3, 4, 5, 6])

In [64]:
a[1]+2

array([ 7,  8,  9, 10, 11])

In [66]:
a=np.array([[1,2],[3,5]])
b=np.array([[7,6],[1,3]])
a

array([[1, 2],
       [3, 5]])

In [67]:
b

array([[7, 6],
       [1, 3]])

In [68]:
a*b

array([[ 7, 12],
       [ 3, 15]])

In [69]:
a@b

array([[ 9, 12],
       [26, 33]])

In [70]:
a.dot(b)

array([[ 9, 12],
       [26, 33]])

In [71]:
np.dot(a,b)

array([[ 9, 12],
       [26, 33]])

In [72]:
a.sum()

11

In [73]:
a.sum(0)

array([4, 7])

In [74]:
a.sum(1)

array([3, 8])

In [75]:
b.cumsum(0)

array([[7, 6],
       [8, 9]])

In [76]:
b.cumsum(1)

array([[ 7, 13],
       [ 1,  4]])